import localFont from "next/font/local";
import Navbar from "./Navbar/page";
import "./globals.css";
import TwoSumPage from "./TwoSum/page";
import AddTwoNum from "./AddTwoNum/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <Navbar />
        <TwoSumPage />
        <AddTwoNum />
      </body>
    </html>
  );
}
